on:
  push:
    branches:
      - main

jobs:
  deploy-docker:
    name: Deploy Ansible
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          # Optional, directory where playbooks live
          directory: ./ansible/
          # Optional, SSH private key
          key: ${{ secrets.SSH_MACOS }}
          # Optional, literal inventory file contents
          options: |
            --inventory inventory

  deploy-app:
    name: Deploy Ansible
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook2.yml
          # Optional, directory where playbooks live
          directory: ./ansible/
          # Optional, SSH private key
          key: ${{ secrets.SSH_MACOS }}
          # Optional, literal inventory file contents
          options: |
            --inventory inventory